
### csrf-cookie
#
GET https://allergenics-v4.test/sanctum/csrf-cookie
Accept: application/json

> {% client.global.set("xsrf_token", decodeURIComponent(response.headers.valueOf('Set-Cookie').split('=')[1].split(';')[0])); %}


### Login
#
POST https://allergenics-v4.test/login
Content-Type: application/x-www-form-urlencoded
Accept: application/json
X-XSRF-TOKEN: {{xsrf_token}}

email={{carlsemail}}&password={{carlspassword}}

###



